In [74]:
import itertools
import numpy as np
import sys
from collections import deque
import queue
import winsound

In [75]:
global itr
itr = 0

global stateSpace 
stateSpace = []

global minHeu
minHeu = sys.maxsize

global minHeuState
minHeuState = []

In [76]:
from math import sqrt
import itertools

def findHeuristic(cs, gs):
    
    #create function to calculate Manhattan distance 
    def manhattan(a, b):
        return sum(abs(val1-val2) for val1, val2 in zip(a,b))

    #define vectors
    A = cs
    B = gs
#     A = [[None, 1, 2], [3, 4, 5], [6, 7, 8]]
#     B = [[  7 , 2, 4], [ 5, None , 6], [ 8  , 3 , 1]]

    # flatennning the list of lists to a single list
    mergedA = list(itertools.chain.from_iterable(A))
    mergedB = list(itertools.chain.from_iterable(B))


    # initialize filtered list
    filtered_listA = []
    filtered_listB = []

    # Using for loop
    for eleA, eleB in zip(mergedA,mergedB):
        if(eleA != None and eleB != None):
            filtered_listA.append(eleA)
            filtered_listB.append(eleB)

        elif(eleA != None and eleB == None):
            filtered_listA.append(eleA)
            filtered_listB.append(0)

        elif(eleA == None and eleB != None):
            filtered_listA.append(0)
            filtered_listB.append(eleB)

        elif(eleA == None and eleB == None):
            filtered_listA.append(0)
            filtered_listB.append(0)


#     print(filtered_listA, filtered_listB, sep = "\n")
    
    gsHeu = manhattan(filtered_listA, filtered_listB)
    
#     code exit if goal stat is found ie., heu is zero
    if(gsHeu == 0):
        solution = copy.deepcopy(cs)
        print("kudos, goal reached!")
        print(cs)
        sys.exit()
        
    global minHeu, minHeuState
    if(minHeu >= gsHeu):
        minHeu = gsHeu
        minHeuState = mergedA
#         print(f"minimum heuristic is {minHeu} - for state is {minHeuState}")
        
    #calculate Manhattan distance between vectors
    return manhattan(filtered_listA, filtered_listB)

In [77]:
def noneInd(arr):
#     print(arr)
    # np.where() to find out index of required value
    result = np.where(arr == None)
#     print("\nindex of the blank block is\n", result)

    # row and column index
    ri = int((result)[0])
    # print("\nrow index\n", ri)

    ci = int((result)[1])
    # print("\ncolumn index\n", ci)

    copyArr = copy.deepcopy(arr)
    # (copyArr)
    return ri, ci

# noneInd()

In [78]:
# checkpoints to make move

def  findNextMoves(q, copyArr, gs): 
#     print("\n",q, copyArr, gs, sep = "\n")
    global itr
    itr = itr + 1
#     print(f"=========================================itr : {itr}+++++++++++++++++++++++++++++++")
    print("\ncurrent state :\n",copyArr)
    print()
#     print("=====================================")

#     to check if current input state and goal state is same
    arr = copy.deepcopy(copyArr)
#     print(arr, type(arr), gs, type(gs), sep = "\n")

    if(list(itertools.chain.from_iterable(arr)) == list(itertools.chain.from_iterable(gs))):
        print("kudos, goal reached!", arr) 
        sys.exit()
        
        
#     print("\nthe below are the set of possible moves with the above current state\n")
    arr = copy.deepcopy(copyArr)
    ri, ci = noneInd(arr)
    if((ri != 0 and ci != 0) or (ci != 0)):
        arr[ri][ci], arr[ri][ci-1] = arr[ri][ci-1], arr[ri][ci]
#         flatenning the nd array and appending to list if the array already doesnot exists
        fll = list(itertools.chain.from_iterable(arr))
        if(fll in stateSpace) == False:
            stateSpace.append(fll)
#             print("left",arr)
#             print("the heuristic value of the current state is  : ",findHeuristic(arr, gs))
            q.put(fll)
            print(q)
#             findNextMoves(arr, gs)
        else:
            pass
#             print("\nnot expanding. present already!\n",fll)
#             print(stateSpace)
    else:
        pass
#         print("\nleft movement impossible!\n")
    print()

    arr = copy.deepcopy(copyArr)
    ri, ci = noneInd(arr)
    if((ci != len(arr[ri])-1) or (ci != len(arr[ri])-1) or (ri != len(arr[ri])-1 and ci != len(arr[ri])-1)):
        arr[ri][ci], arr[ri][ci+1] = arr[ri][ci+1], arr[ri][ci]
        fll = list(itertools.chain.from_iterable(arr))
        if(fll in stateSpace) == False:
            stateSpace.append(fll)
#             print("right",arr)
#             print("the heuristic value of the current state is  : ",findHeuristic(arr, gs))
            q.put(fll)
#             findNextMoves(arr, gs)
        else:
            pass
#             print("\nnot expanding. present already!\n",fll)
#             print(stateSpace)
    else:
        pass
#         print("\nright movement impossible!\n")
    print()

    arr = copy.deepcopy(copyArr)
    ri, ci = noneInd(arr)
    if((ri != 0 and ci != 0) or (ri != 0)):
        arr[ri][ci], arr[ri-1][ci] = arr[ri-1][ci], arr[ri][ci]
        fll = list(itertools.chain.from_iterable(arr))
        if(fll in stateSpace) == False:
            stateSpace.append(fll)
#             print("up",arr)
#             print("the heuristic value of the current state is  : ",findHeuristic(arr, gs))
#             print("====================================================")
#             print()
#             print("before",list(q.queue), len(list(q.queue)))
#             print()
            q.put(fll)
#             print()
#             print("after",list(q.queue), len(list(q.queue)))
#             print()
#             print("====================================================")
#             findNextMoves(arr, gs)
        else:
            pass
#             print("\nnot expanding. present already!\n",fll)
#             print(stateSpace)
    else:
        pass
#         print("\nup movement impossible!\n")
    print()

    arr = copy.deepcopy(copyArr)
    ri, ci = noneInd(arr)
    if((ri != len(arr[ri])-1) or (ri != len(arr[ri])-1 and ci != len(arr[ri])-1)):
        arr[ri][ci], arr[ri+1][ci] = arr[ri+1][ci], arr[ri][ci]
        fll = list(itertools.chain.from_iterable(arr))
        if(fll in stateSpace) == False:
            stateSpace.append(fll)
#             print("down",arr)
#             print("the heuristic value of the current state is  : ",findHeuristic(arr, gs))
            q.put(fll)
#             findNextMoves(arr, gs)
        else:
            pass
#             print("\nnot expanding. present already!\n",fll)
#             print(stateSpace)
    else:
        pass
#         print("\ndown movement impossible!\n")
    print()
#     print(stateSpace)
#     print("=====================================")
#     print(f"\n states in queue:\n {list(q.queue)} and len is {len(list(q.queue))}")
    return q

In [85]:
# qqqq = deque(qqqq)
# opening file to write the output in it
with open('outputFile.txt', 'w') as f:
    f.write("output file")
    
gl = [None, 1, 2, 3, 4, 5, 6, 7, 8]
while(len(list(q.queue)) != 0):
#     print("\n================initial queue:\n",list(q.queue))
    val = q.get()
    print("\nnext state to be passed:\n",val, gl)
    frequency = 2500  # Set Frequency To 2500 Hertz
    duration = 1000  # Set Duration To 1000 ms == 1 second
    winsound.Beep(frequency, duration)
    
#     appending values to the file
    with open('outputFile.txt', 'a') as f:
        f.write(str(val)+"\n")
    
#     checking condition to terminate
    if(val == gl):
        print("outputtttttttttttttttttttt founddddd!!!", val)
        f.close()
        
#         producing sound when goal state is reached
        frequency = 2500  # Set Frequency To 2500 Hertz
        duration = 10000  # Set Duration To 1000 ms == 1 second
        winsound.MessageBeep(duration)
        sys.exit()
    
    
    val = np.asarray(val).reshape(3, 3)
#     print("\n=========+++++++++++++++=======after queue:\n",list(q.queue))
    findNextMoves(q, val, gs)
        
#         producing sound when end of the code is reached
frequency = 2500  # Set Frequency To 2500 Hertz
duration = 10000  # Set Duration To 1000 ms == 1 second





next state to be passed:
 [1, 2, 3, 4, None, 5, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [4 None 5]
 [6 7 8]]






next state to be passed:
 [1, 2, 3, None, 4, 5, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [None 4 5]
 [6 7 8]]






next state to be passed:
 [1, 2, 3, 4, 5, None, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [4 5 None]
 [6 7 8]]






next state to be passed:
 [1, None, 3, 4, 2, 5, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 3]
 [4 2 5]
 [6 7 8]]






next state to be passed:
 [1, 2, 3, 4, 7, 5, 6, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [4 7 5]
 [6 None 8]]






next state to be passed:
 [None, 2, 3, 1, 4, 5, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 2 3]
 [1 4 5]
 [6 7 8]]






next state to be passed:
 [1, 2, 3, 6, 4, 5, None, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 4 5]
 [None 7 8]]







current state :
 [[1 2 3]
 [4 8 None]
 [6 5 7]]






next state to be passed:
 [1, None, 3, 4, 2, 8, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 3]
 [4 2 8]
 [6 5 7]]






next state to be passed:
 [4, 1, 3, 2, 5, None, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [2 5 None]
 [6 7 8]]






next state to be passed:
 [4, None, 3, 2, 1, 5, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 3]
 [2 1 5]
 [6 7 8]]






next state to be passed:
 [4, 1, 3, 2, 7, 5, 6, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [2 7 5]
 [6 None 8]]






next state to be passed:
 [4, 1, 3, 6, 2, 5, 7, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [6 2 5]
 [7 None 8]]






next state to be passed:
 [1, 3, 5, None, 4, 2, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 5]
 [None 4 2]
 [6 7 8]]






next state to be passed:
 [1, None, 5, 4, 3, 2, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 3 None]
 [2 1 5]
 [6 7 8]]






next state to be passed:
 [4, 1, 3, 2, 7, 5, None, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [2 7 5]
 [None 6 8]]






next state to be passed:
 [4, 1, 3, 2, 7, 5, 6, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [2 7 5]
 [6 8 None]]






next state to be passed:
 [4, 1, 3, 6, 2, 5, 7, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [6 2 5]
 [7 8 None]]






next state to be passed:
 [4, 1, 3, 6, None, 5, 7, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [6 None 5]
 [7 2 8]]






next state to be passed:
 [None, 3, 5, 1, 4, 2, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 3 5]
 [1 4 2]
 [6 7 8]]






next state to be passed:
 [1, 3, 5, 6, 4, 2, None, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 5]
 [6 4 2]
 [None 7 8]]






next state to be passed:
 [None, 1, 5, 4, 3, 2, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 5 2]
 [None 7 3]
 [4 6 8]]






next state to be passed:
 [1, 5, 2, 4, 7, None, 6, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 5 2]
 [4 7 None]
 [6 8 3]]






next state to be passed:
 [1, 2, 3, 5, 8, None, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [5 8 None]
 [4 6 7]]






next state to be passed:
 [1, None, 3, 5, 2, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 3]
 [5 2 8]
 [4 6 7]]






next state to be passed:
 [1, 2, 3, 5, 6, 8, 4, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [5 6 8]
 [4 None 7]]






next state to be passed:
 [2, None, 3, 1, 5, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 3]
 [1 5 8]
 [4 6 7]]






next state to be passed:
 [2, None, 3, 1, 4, 8, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 3]
 [1 4 8]
 [6 5 7]]






next state to be passed:
 [1, 2, 3, 6, 4, 8, 5, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 3 5]
 [1 7 4]
 [6 8 None]]






next state to be passed:
 [2, 3, 5, 1, 4, 8, None, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [1 4 8]
 [None 6 7]]






next state to be passed:
 [2, 3, 5, 1, None, 8, 6, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [1 None 8]
 [6 4 7]]






next state to be passed:
 [2, 4, 3, 6, 1, 5, 7, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 3]
 [6 1 5]
 [7 8 None]]






next state to be passed:
 [2, 4, 3, 6, None, 5, 7, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 3]
 [6 None 5]
 [7 1 8]]






next state to be passed:
 [None, 2, 4, 1, 5, 3, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 2 4]
 [1 5 3]
 [6 7 8]]






next state to be passed:
 [2, 5, 4, 1, None, 3, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 4]
 [1 None 3]
 [6 7 8]]






next state to be passed:
 [2, 4, 3, 1, 5, 8, None, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 2 3]
 [5 6 8]
 [None 4 7]]






next state to be passed:
 [1, 2, 3, 5, 6, 8, 4, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [5 6 8]
 [4 7 None]]






next state to be passed:
 [2, 3, None, 1, 5, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 None]
 [1 5 8]
 [4 6 7]]






next state to be passed:
 [2, 5, 3, 1, None, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 3]
 [1 None 8]
 [4 6 7]]






next state to be passed:
 [2, 3, None, 1, 4, 8, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 None]
 [1 4 8]
 [6 5 7]]






next state to be passed:
 [1, 2, 3, 6, 4, 8, 5, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 4 8]
 [5 7 None]]






next state to be passed:
 [1, 2, 3, 6, None, 8, 5, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 None 8]
 [5 4 7]]






next state to be passed:
 [None, 1, 2, 4, 8, 3, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 2 3]
 [7 None 6]
 [4 8 5]]






next state to be passed:
 [1, 2, None, 7, 6, 3, 4, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 None]
 [7 6 3]
 [4 8 5]]






next state to be passed:
 [2, 3, 5, 1, None, 7, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [1 None 7]
 [4 6 8]]






next state to be passed:
 [2, 3, 5, 1, 7, 8, 4, 6, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [1 7 8]
 [4 6 None]]






next state to be passed:
 [None, 7, 3, 2, 1, 5, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 7 3]
 [2 1 5]
 [4 6 8]]






next state to be passed:
 [2, 7, 3, 4, 1, 5, None, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 3]
 [4 1 5]
 [None 6 8]]






next state to be passed:
 [2, 7, None, 1, 5, 3, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 None]
 [1 5 3]
 [4 6 8]]






next state to be passed:
 [2, 7, 3, 1, 5, 8, 4, 6, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 None 3]
 [1 6 4]
 [7 8 5]]






next state to be passed:
 [1, 2, 3, 7, 6, 4, 8, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [7 6 4]
 [8 None 5]]






next state to be passed:
 [6, 1, 3, None, 2, 4, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [None 2 4]
 [7 8 5]]






next state to be passed:
 [1, 3, 4, 6, 2, None, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 4]
 [6 2 None]
 [7 8 5]]






next state to be passed:
 [1, 2, 3, None, 8, 4, 6, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [None 8 4]
 [6 7 5]]






next state to be passed:
 [1, 2, 3, 6, 8, None, 7, 5, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 8 None]
 [7 5 4]]






next state to be passed:
 [6, 1, 2, None, 4, 3, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 2]
 [None 4 3]
 [7 8 5]]






next state to be passed:
 [1, 4, 2, None, 6, 3, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 None 2]
 [5 8 3]
 [4 6 7]]






next state to be passed:
 [1, 2, 3, 5, 8, 7, 4, None, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [5 8 7]
 [4 None 6]]






next state to be passed:
 [5, 1, 3, None, 2, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 1 3]
 [None 2 8]
 [4 6 7]]






next state to be passed:
 [1, 3, 8, 5, 2, None, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 8]
 [5 2 None]
 [4 6 7]]






next state to be passed:
 [1, 2, 3, None, 6, 8, 5, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [None 6 8]
 [5 4 7]]






next state to be passed:
 [1, 2, 3, 5, 6, None, 4, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [5 6 None]
 [4 7 8]]






next state to be passed:
 [2, 3, 8, 1, 5, None, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 8]
 [1 5 None]
 [4 6 7]]






next state to be passed:
 [2, 5, 3, None, 1, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[3 5 2]
 [1 4 None]
 [6 7 8]]






next state to be passed:
 [3, 4, 5, None, 1, 2, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [None 1 2]
 [6 7 8]]






next state to be passed:
 [3, 4, 5, 1, 2, None, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [1 2 None]
 [6 7 8]]






next state to be passed:
 [3, 4, 5, 1, 7, 2, 6, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [1 7 2]
 [6 None 8]]






next state to be passed:
 [1, 3, 5, 6, 4, None, 7, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 5]
 [6 4 None]
 [7 8 2]]






next state to be passed:
 [4, 1, 5, 3, 2, None, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 5]
 [3 2 None]
 [6 7 8]]






next state to be passed:
 [4, None, 5, 3, 1, 2, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 5]
 [3 1 2]
 [6 7 8]]






next state to be passed:
 [4, 1, 5, 3, 7, 2, 6, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 2 3]
 [None 6 7]
 [8 4 5]]






next state to be passed:
 [1, 2, 3, 6, 7, None, 8, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 7 None]
 [8 4 5]]






next state to be passed:
 [1, None, 3, 6, 2, 7, 8, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 3]
 [6 2 7]
 [8 4 5]]






next state to be passed:
 [4, 1, 3, 6, 2, 7, 8, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [6 2 7]
 [8 None 5]]






next state to be passed:
 [1, 3, 7, None, 4, 2, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 7]
 [None 4 2]
 [6 8 5]]






next state to be passed:
 [1, None, 7, 4, 3, 2, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 7]
 [4 3 2]
 [6 8 5]]






next state to be passed:
 [1, 3, 7, 4, 8, 2, 6, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 7]
 [4 8 2]
 [6 None 5]]






next state to be passed:
 [1, 3, 7, 4, 2, 5, 6, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 5 4]
 [1 7 3]
 [None 6 8]]






next state to be passed:
 [2, 5, 4, 1, 7, 3, 6, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 4]
 [1 7 3]
 [6 8 None]]






next state to be passed:
 [2, 4, 3, 5, None, 8, 1, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 3]
 [5 None 8]
 [1 6 7]]






next state to be passed:
 [None, 4, 3, 2, 5, 8, 1, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 4 3]
 [2 5 8]
 [1 6 7]]






next state to be passed:
 [None, 4, 3, 2, 1, 8, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 4 3]
 [2 1 8]
 [6 5 7]]






next state to be passed:
 [2, 4, 3, 6, 1, 8, None, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 3]
 [6 1 8]
 [None 5 7]]






next state to be passed:
 [2, 4, None, 1, 8, 3, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 None]
 [1 8 3]
 [6 5 7]]






next state to be passed:
 [2, 4, 3, 1, 8, 7, 6, 5, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 2 3]
 [5 None 8]
 [6 7 4]]






next state to be passed:
 [None, 2, 3, 1, 5, 8, 6, 7, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 2 3]
 [1 5 8]
 [6 7 4]]






next state to be passed:
 [None, 2, 3, 1, 6, 8, 7, 5, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 2 3]
 [1 6 8]
 [7 5 4]]






next state to be passed:
 [1, 2, 3, 7, 6, 8, None, 5, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [7 6 8]
 [None 5 4]]






next state to be passed:
 [None, 1, 3, 6, 2, 8, 7, 5, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 3]
 [6 2 8]
 [7 5 4]]






next state to be passed:
 [1, 3, None, 6, 2, 8, 7, 5, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 None]
 [6 2 8]
 [7 5 4]]






next state to be passed:
 [6, 1, None, 2, 5, 3, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 None]
 [2 5 3]
 [7 4 8]]






next state to be passed:
 [6, 1, 3, 2, 5, 8, 7, 4, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[None 1 2]
 [4 5 8]
 [6 3 7]]






next state to be passed:
 [1, 2, None, 4, 5, 8, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 None]
 [4 5 8]
 [6 3 7]]






next state to be passed:
 [1, 5, None, 7, 3, 2, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 5 None]
 [7 3 2]
 [4 6 8]]






next state to be passed:
 [1, 5, 2, 7, 3, 8, 4, 6, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 5 2]
 [7 3 8]
 [4 6 None]]






next state to be passed:
 [1, 5, 2, 7, 6, 3, 4, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 5 2]
 [7 6 3]
 [4 8 None]]






next state to be passed:
 [5, 2, None, 1, 7, 3, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 2 None]
 [1 7 3]
 [4 6 8]]






next state to be passed:
 [5, 7, 2, 1, None, 3, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 7 2]
 [1 None 3]
 [4 6 8]]






next state to be passed:
 [None, 5, 2, 1, 4, 7, 6, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 3 None]
 [2 1 8]
 [6 5 7]]






next state to be passed:
 [4, 1, 3, 6, 2, 8, 5, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [6 2 8]
 [5 7 None]]






next state to be passed:
 [4, 1, 3, 6, None, 8, 5, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [6 None 8]
 [5 2 7]]






next state to be passed:
 [None, 3, 8, 1, 4, 2, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 3 8]
 [1 4 2]
 [6 5 7]]






next state to be passed:
 [1, 3, 8, 6, 4, 2, None, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 8]
 [6 4 2]
 [None 5 7]]






next state to be passed:
 [None, 1, 8, 4, 3, 2, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 8]
 [4 3 2]
 [6 5 7]]






next state to be passed:
 [1, 3, 8, 4, 5, 2, None, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 8]
 [4 5 2]
 [None 6 7]]






next state to be passed:
 [1, 3, 8, 4, 5, 2, 6, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 3 5]
 [6 None 1]
 [7 2 8]]






next state to be passed:
 [4, 3, 5, 6, 1, 8, 7, 2, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [6 1 8]
 [7 2 None]]






next state to be passed:
 [3, 5, 2, 1, None, 4, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 5 2]
 [1 None 4]
 [6 7 8]]






next state to be passed:
 [3, 5, 2, 1, 4, 8, 6, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 5 2]
 [1 4 8]
 [6 7 None]]






next state to be passed:
 [None, 4, 5, 3, 1, 2, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 4 5]
 [3 1 2]
 [6 7 8]]






next state to be passed:
 [3, 4, 5, 6, 1, 2, None, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [6 1 2]
 [None 7 8]]






next state to be passed:
 [3, 4, None, 1, 2, 5, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 None]
 [1 2 5]
 [6 7 8]]






next state to be passed:
 [3, 4, 5, 1, 2, 8, 6, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[None 2 3]
 [1 7 8]
 [4 5 6]]






next state to be passed:
 [1, 2, 3, 4, 7, 8, None, 5, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [4 7 8]
 [None 5 6]]






next state to be passed:
 [1, 2, None, 7, 8, 3, 4, 5, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 None]
 [7 8 3]
 [4 5 6]]






next state to be passed:
 [1, 2, 3, 7, 8, 6, 4, 5, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [7 8 6]
 [4 5 None]]






next state to be passed:
 [None, 1, 3, 7, 2, 8, 4, 5, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 3]
 [7 2 8]
 [4 5 6]]






next state to be passed:
 [1, 3, None, 7, 2, 8, 4, 5, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 None]
 [7 2 8]
 [4 5 6]]






next state to be passed:
 [7, 1, None, 2, 5, 3, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 1 None]
 [2 5 3]
 [4 6 8]]






next state to be passed:
 [7, 1, 3, 2, 5, 8, 4, 6, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[None 3 7]
 [1 4 2]
 [6 8 5]]






next state to be passed:
 [1, 3, 7, 6, 4, 2, None, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 7]
 [6 4 2]
 [None 8 5]]






next state to be passed:
 [None, 1, 7, 4, 3, 2, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 7]
 [4 3 2]
 [6 8 5]]






next state to be passed:
 [1, 3, 7, 4, 8, 2, None, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 7]
 [4 8 2]
 [None 6 5]]






next state to be passed:
 [1, 3, 7, 4, 8, 2, 6, 5, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 7]
 [4 8 2]
 [6 5 None]]






next state to be passed:
 [1, 3, 7, 4, 2, 5, None, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 7]
 [4 2 5]
 [None 6 8]]






next state to be passed:
 [1, 3, 7, 4, None, 5, 6, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 7]
 [4 None 5]
 [6 2 8]]






next state to be passed:
 [1, 2, None, 8, 7, 3, 4, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 None 3]
 [1 7 5]
 [6 8 4]]






next state to be passed:
 [2, 3, 5, 4, 8, None, 1, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [4 8 None]
 [1 6 7]]






next state to be passed:
 [2, None, 5, 4, 3, 8, 1, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 5]
 [4 3 8]
 [1 6 7]]






next state to be passed:
 [2, 3, 5, 4, 6, 8, 1, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [4 6 8]
 [1 None 7]]






next state to be passed:
 [3, None, 5, 2, 4, 8, 1, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 None 5]
 [2 4 8]
 [1 6 7]]






next state to be passed:
 [3, None, 5, 2, 1, 8, 6, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 None 5]
 [2 1 8]
 [6 4 7]]






next state to be passed:
 [2, 3, 5, 6, 1, 8, 4, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [6 1 8]
 [4 None 7]]






next state to be passed:
 [2, None, 3, 1, 8, 5, 6, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 2 3]
 [None 7 4]
 [8 6 5]]






next state to be passed:
 [1, 2, 3, 7, 4, None, 8, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [7 4 None]
 [8 6 5]]






next state to be passed:
 [1, None, 3, 7, 2, 4, 8, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 3]
 [7 2 4]
 [8 6 5]]






next state to be passed:
 [6, 1, 3, 2, 4, None, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [2 4 None]
 [7 8 5]]






next state to be passed:
 [6, None, 3, 2, 1, 4, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 None 3]
 [2 1 4]
 [7 8 5]]






next state to be passed:
 [6, 1, 3, 2, 8, 4, 7, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [2 8 4]
 [7 None 5]]






next state to be passed:
 [6, 1, 3, 7, 2, 4, 8, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [7 2 4]
 [8 None 5]]






next state to be passed:
 [1, 3, 4, None, 6, 2, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[6 1 3]
 [None 4 5]
 [2 7 8]]






next state to be passed:
 [6, 1, 3, 7, 2, None, 4, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [7 2 None]
 [4 8 5]]






next state to be passed:
 [6, 1, 3, None, 7, 5, 4, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [None 7 5]
 [4 2 8]]






next state to be passed:
 [6, 1, 3, 7, 5, None, 4, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [7 5 None]
 [4 2 8]]






next state to be passed:
 [6, None, 3, 7, 1, 5, 4, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 None 3]
 [7 1 5]
 [4 2 8]]






next state to be passed:
 [3, None, 5, 1, 6, 2, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 None 5]
 [1 6 2]
 [7 4 8]]






next state to be passed:
 [6, 1, 5, None, 3, 2, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 5]
 [None 3 2]
 [7 4 8]]






next state to be passed:
 [1, 3, 5, None, 2, 8, 6, 7, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 5 2]
 [6 8 4]
 [7 None 3]]






next state to be passed:
 [1, None, 5, 6, 4, 2, 7, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 5]
 [6 4 2]
 [7 8 3]]






next state to be passed:
 [1, 5, 2, 3, 8, None, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 5 2]
 [3 8 None]
 [4 6 7]]






next state to be passed:
 [1, None, 2, 3, 5, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 2]
 [3 5 8]
 [4 6 7]]






next state to be passed:
 [1, 5, 2, 3, 6, 8, 4, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 5 2]
 [3 6 8]
 [4 None 7]]






next state to be passed:
 [5, None, 2, 1, 3, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 None 2]
 [1 3 8]
 [4 6 7]]






next state to be passed:
 [5, None, 2, 1, 4, 8, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 None 2]
 [1 4 8]
 [6 3 7]]






next state to be passed:
 [1, 5, 2, 6, 4, 8, 3, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 5 3]
 [1 8 7]
 [4 None 6]]






next state to be passed:
 [2, 5, 3, None, 6, 8, 1, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 3]
 [None 6 8]
 [1 4 7]]






next state to be passed:
 [2, 5, 3, 1, 6, None, 4, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 3]
 [1 6 None]
 [4 7 8]]






next state to be passed:
 [2, 3, 8, None, 1, 4, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 8]
 [None 1 4]
 [6 5 7]]






next state to be passed:
 [2, None, 8, 1, 3, 4, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 8]
 [1 3 4]
 [6 5 7]]






next state to be passed:
 [2, 3, 8, 1, 5, 4, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 8]
 [1 5 4]
 [6 None 7]]






next state to be passed:
 [2, 3, 8, 1, 4, 7, 6, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 8]
 [1 4 7]
 [6 None 5]]






next state to be passed:
 [1, 2, 3, None, 6, 4, 5, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[3 None 5]
 [4 2 1]
 [6 7 8]]






next state to be passed:
 [4, 3, 5, 6, 2, 1, 7, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [6 2 1]
 [7 None 8]]






next state to be passed:
 [2, 4, 5, None, 3, 1, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 5]
 [None 3 1]
 [6 7 8]]






next state to be passed:
 [4, 3, 5, None, 7, 1, 2, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [None 7 1]
 [2 6 8]]






next state to be passed:
 [4, 3, 5, 2, 7, None, 6, 8, 1] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [2 7 None]
 [6 8 1]]






next state to be passed:
 [4, 3, 5, None, 1, 8, 2, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [None 1 8]
 [2 6 7]]






next state to be passed:
 [4, 3, 5, None, 2, 8, 6, 1, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [None 2 8]
 [6 1 7]]






next state to be passed:
 [4, 3, 5, 2, 8, None, 6, 1, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[3 5 2]
 [1 7 4]
 [6 None 8]]






next state to be passed:
 [3, 5, 2, 1, 4, 8, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 5 2]
 [1 4 8]
 [6 None 7]]






next state to be passed:
 [3, 4, 5, 6, 1, 2, 7, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [6 1 2]
 [7 None 8]]






next state to be passed:
 [3, None, 4, 1, 2, 5, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 None 4]
 [1 2 5]
 [6 7 8]]






next state to be passed:
 [3, 4, 5, 1, 2, 8, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [1 2 8]
 [6 None 7]]






next state to be passed:
 [3, 4, 5, None, 7, 2, 1, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [None 7 2]
 [1 6 8]]






next state to be passed:
 [3, 4, 5, 1, 7, None, 6, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [1 7 None]
 [6 8 2]]






next state to be passed:
 [1, 3, 5, None, 6, 4, 7, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 None 5]
 [6 3 8]
 [2 4 7]]






next state to be passed:
 [4, 1, 3, None, 8, 5, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [None 8 5]
 [6 2 7]]






next state to be passed:
 [1, 8, 3, None, 4, 5, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 3]
 [None 4 5]
 [6 2 7]]






next state to be passed:
 [1, 8, 3, 4, 5, None, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 3]
 [4 5 None]
 [6 2 7]]






next state to be passed:
 [1, 8, 3, 4, 2, 5, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 3]
 [4 2 5]
 [6 None 7]]






next state to be passed:
 [4, 1, 5, 3, 8, None, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 5]
 [3 8 None]
 [6 2 7]]






next state to be passed:
 [4, None, 5, 3, 1, 8, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 5]
 [3 1 8]
 [6 2 7]]






next state to be passed:
 [4, 1, 5, 6, 3, 8, 2, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 3 5]
 [1 6 None]
 [4 8 7]]






next state to be passed:
 [2, 3, 5, None, 7, 8, 1, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [None 7 8]
 [1 4 6]]






next state to be passed:
 [2, 3, 5, None, 1, 8, 4, 7, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [None 1 8]
 [4 7 6]]






next state to be passed:
 [2, 3, 5, 1, 8, None, 4, 7, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [1 8 None]
 [4 7 6]]






next state to be passed:
 [2, None, 5, 1, 3, 8, 4, 7, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 5]
 [1 3 8]
 [4 7 6]]






next state to be passed:
 [2, 7, 3, 4, 1, None, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 3]
 [4 1 None]
 [6 8 5]]






next state to be passed:
 [2, 7, 3, None, 4, 5, 6, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 3]
 [None 4 5]
 [6 1 8]]






next state to be passed:
 [2, 7, 3, 4, 5, None, 6, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 3 7]
 [8 2 None]
 [4 6 5]]






next state to be passed:
 [1, 2, 3, 8, 6, None, 4, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [8 6 None]
 [4 5 7]]






next state to be passed:
 [2, 3, 7, 1, 8, None, 4, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 7]
 [1 8 None]
 [4 6 5]]






next state to be passed:
 [2, 8, 3, None, 1, 7, 4, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 8 3]
 [None 1 7]
 [4 6 5]]






next state to be passed:
 [2, 8, 3, 1, 7, None, 4, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 8 3]
 [1 7 None]
 [4 6 5]]






next state to be passed:
 [2, 8, 3, 1, 6, 7, 4, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 8 3]
 [1 6 7]
 [4 None 5]]






next state to be passed:
 [4, None, 1, 7, 3, 2, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 1]
 [7 3 2]
 [6 8 5]]






next state to be passed:
 [4, 1, 2, 7, 3, 5, 6, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 5 None]
 [3 2 4]
 [6 7 8]]






next state to be passed:
 [1, 2, 5, 3, 7, 4, None, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 5]
 [3 7 4]
 [None 6 8]]






next state to be passed:
 [1, 2, 5, 3, 7, 4, 6, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 5]
 [3 7 4]
 [6 8 None]]






next state to be passed:
 [1, 2, 5, 6, 3, 4, 7, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 5]
 [6 3 4]
 [7 8 None]]






next state to be passed:
 [1, 2, 5, 6, None, 4, 7, 3, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 5]
 [6 None 4]
 [7 3 8]]






next state to be passed:
 [2, 5, 4, 1, 3, 8, None, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 4]
 [1 3 8]
 [None 6 7]]






next state to be passed:
 [2, 5, 4, 1, None, 8, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 4]
 [1 None 8]
 [6 3 7]]






next state to be passed:
 [2, 3, 5, 7, 4, 8, 1, 6, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[6 2 3]
 [7 4 5]
 [None 1 8]]






next state to be passed:
 [1, 2, None, 5, 3, 4, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 None]
 [5 3 4]
 [6 7 8]]






next state to be passed:
 [1, 2, 4, 5, 3, 8, 6, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 4]
 [5 3 8]
 [6 7 None]]






next state to be passed:
 [None, 1, 4, 5, 2, 3, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 4]
 [5 2 3]
 [6 7 8]]






next state to be passed:
 [1, 4, None, 5, 2, 3, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 4 None]
 [5 2 3]
 [6 7 8]]






next state to be passed:
 [1, 2, 4, 5, 7, 3, None, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 4]
 [5 7 3]
 [None 6 8]]






next state to be passed:
 [1, 2, 4, 5, 7, 3, 6, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 4]
 [5 7 3]
 [6 8 None]]






next state to be passed:
 [1, 2, 4, 6, 5, 3, 7, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 7 4]
 [1 8 3]
 [None 6 5]]






next state to be passed:
 [2, 7, 4, 1, 8, 3, 6, 5, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 4]
 [1 8 3]
 [6 5 None]]






next state to be passed:
 [2, 3, 4, 1, None, 6, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 4]
 [1 None 6]
 [7 8 5]]






next state to be passed:
 [2, 3, 4, 1, 6, 5, 7, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 4]
 [1 6 5]
 [7 8 None]]






next state to be passed:
 [None, 6, 3, 2, 1, 4, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 6 3]
 [2 1 4]
 [7 8 5]]






next state to be passed:
 [2, 6, 3, 7, 1, 4, None, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 6 3]
 [7 1 4]
 [None 8 5]]






next state to be passed:
 [2, 6, None, 1, 4, 3, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 6 None]
 [1 4 3]
 [7 8 5]]






next state to be passed:
 [2, 6, 3, 1, 8, 4, None, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 4 2]
 [6 None 5]
 [7 3 8]]






next state to be passed:
 [1, 4, 2, 8, None, 3, 6, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 4 2]
 [8 None 3]
 [6 7 5]]






next state to be passed:
 [None, 4, 2, 1, 8, 3, 6, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 4 2]
 [1 8 3]
 [6 7 5]]






next state to be passed:
 [1, 4, 2, 6, None, 8, 7, 5, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 4 2]
 [6 None 8]
 [7 5 3]]






next state to be passed:
 [1, 4, None, 6, 8, 2, 7, 5, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 4 None]
 [6 8 2]
 [7 5 3]]






next state to be passed:
 [None, 3, 5, 2, 1, 6, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 3 5]
 [2 1 6]
 [7 4 8]]






next state to be passed:
 [2, 3, 5, 7, 1, 6, None, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [7 1 6]
 [None 4 8]]






next state to be passed:
 [None, 2, 5, 1, 3, 6, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[6 3 5]
 [2 1 8]
 [7 4 None]]






next state to be passed:
 [6, 1, 3, 4, None, 5, 2, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [4 None 5]
 [2 7 8]]






next state to be passed:
 [None, 1, 3, 6, 4, 5, 2, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 3]
 [6 4 5]
 [2 7 8]]






next state to be passed:
 [6, 1, 3, 7, None, 2, 4, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [7 None 2]
 [4 8 5]]






next state to be passed:
 [6, 1, None, 7, 2, 3, 4, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 None]
 [7 2 3]
 [4 8 5]]






next state to be passed:
 [None, 1, 3, 6, 7, 5, 4, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 3]
 [6 7 5]
 [4 2 8]]






next state to be passed:
 [6, 1, 3, 4, 7, 5, None, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [4 7 5]
 [None 2 8]]






next state to be passed:
 [6, 1, None, 7, 5, 3, 4, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 1 2]
 [6 5 7]
 [None 8 3]]






next state to be passed:
 [None, 4, 2, 5, 1, 7, 6, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 4 2]
 [5 1 7]
 [6 8 3]]






next state to be passed:
 [4, 2, None, 5, 1, 7, 6, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 2 None]
 [5 1 7]
 [6 8 3]]






next state to be passed:
 [4, 1, 2, 5, 8, 7, None, 6, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 2]
 [5 8 7]
 [None 6 3]]






next state to be passed:
 [None, 4, 1, 5, 7, 2, 6, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 4 1]
 [5 7 2]
 [6 8 3]]






next state to be passed:
 [4, 7, 1, 5, None, 2, 6, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 7 1]
 [5 None 2]
 [6 8 3]]






next state to be passed:
 [None, 1, 2, 4, 6, 5, 7, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 2]
 [4 6 5]
 [7 8 3]]






next state to be passed:
 [4, 1, 2, 7, 6, 5, None, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[5 2 None]
 [1 3 8]
 [4 6 7]]






next state to be passed:
 [5, 3, 2, 1, None, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 3 2]
 [1 None 8]
 [4 6 7]]






next state to be passed:
 [5, 2, None, 1, 4, 8, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 2 None]
 [1 4 8]
 [6 3 7]]






next state to be passed:
 [1, 5, 2, 6, 4, 8, 3, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 5 2]
 [6 4 8]
 [3 7 None]]






next state to be passed:
 [1, 5, 2, 6, None, 8, 3, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 5 2]
 [6 None 8]
 [3 4 7]]






next state to be passed:
 [None, 1, 5, 4, 8, 2, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 5]
 [4 8 2]
 [6 3 7]]






next state to be passed:
 [1, 8, 5, 4, None, 2, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 5]
 [4 None 2]
 [6 3 7]]






next state to be passed:
 [1, 2, 8, 4, None, 5, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[5 1 3]
 [2 8 7]
 [4 6 None]]






next state to be passed:
 [5, 3, None, 2, 1, 8, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 3 None]
 [2 1 8]
 [4 6 7]]






next state to be passed:
 [5, 1, 3, 2, 6, 8, None, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 1 3]
 [2 6 8]
 [None 4 7]]






next state to be passed:
 [5, 1, 3, 2, 6, 8, 4, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 1 3]
 [2 6 8]
 [4 7 None]]






next state to be passed:
 [5, 1, 3, 4, 2, 8, 6, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 1 3]
 [4 2 8]
 [6 7 None]]






next state to be passed:
 [5, 1, 3, 4, None, 8, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 1 3]
 [4 None 8]
 [6 2 7]]






next state to be passed:
 [None, 3, 8, 1, 5, 2, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 3 8]
 [1 5 2]
 [4 6 7]]






next state to be passed:
 [None, 1, 8, 5, 3, 2, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 4 2]
 [6 None 3]
 [5 7 8]]






next state to be passed:
 [None, 1, 2, 6, 8, 3, 5, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 2]
 [6 8 3]
 [5 4 7]]






next state to be passed:
 [1, 8, 2, 6, None, 3, 5, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 2]
 [6 None 3]
 [5 4 7]]






next state to be passed:
 [1, 2, 3, 6, 8, 7, None, 5, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 8 7]
 [None 5 4]]






next state to be passed:
 [1, 2, 3, 6, None, 7, 5, 8, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 None 7]
 [5 8 4]]






next state to be passed:
 [6, 1, 3, 2, None, 8, 5, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [2 None 8]
 [5 4 7]]






next state to be passed:
 [6, 1, 3, 5, 2, 8, None, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [5 2 8]
 [None 4 7]]






next state to be passed:
 [1, 3, 8, 6, None, 2, 5, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 4 1]
 [5 3 8]
 [6 7 None]]






next state to be passed:
 [None, 2, 1, 5, 4, 3, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 2 1]
 [5 4 3]
 [6 7 8]]






next state to be passed:
 [2, 1, None, 5, 4, 3, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 1 None]
 [5 4 3]
 [6 7 8]]






next state to be passed:
 [2, 4, 1, 5, 7, 3, None, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 1]
 [5 7 3]
 [None 6 8]]






next state to be passed:
 [2, 4, 1, 5, 7, 3, 6, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 1]
 [5 7 3]
 [6 8 None]]






next state to be passed:
 [2, 4, 1, 6, 5, 3, 7, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 1]
 [6 5 3]
 [7 8 None]]






next state to be passed:
 [2, 4, 1, 6, None, 3, 7, 5, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 1]
 [6 None 3]
 [7 5 8]]






next state to be passed:
 [5, 1, None, 4, 2, 3, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 7 None]
 [4 5 3]
 [2 6 8]]






next state to be passed:
 [1, 7, 3, 4, 5, 8, 2, 6, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 3]
 [4 5 8]
 [2 6 None]]






next state to be passed:
 [1, 7, 3, 4, 6, 5, None, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 3]
 [4 6 5]
 [None 2 8]]






next state to be passed:
 [1, 7, 3, 4, 6, 5, 2, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 3]
 [4 6 5]
 [2 8 None]]






next state to be passed:
 [4, 3, 7, 2, None, 1, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 7]
 [2 None 1]
 [6 8 5]]






next state to be passed:
 [4, 3, 7, 2, 1, 5, 6, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 7]
 [2 1 5]
 [6 8 None]]






next state to be passed:
 [4, 1, 3, 8, None, 7, 2, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [8 None 7]
 [2 6 5]]






next state to be passed:
 [None, 1, 3, 4, 8, 7, 2, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[None 4 3]
 [6 1 8]
 [7 5 2]]






next state to be passed:
 [4, 3, None, 6, 1, 8, 7, 5, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 None]
 [6 1 8]
 [7 5 2]]






next state to be passed:
 [6, 4, None, 1, 5, 3, 7, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 None]
 [1 5 3]
 [7 2 8]]






next state to be passed:
 [6, 4, 3, 1, 5, 8, 7, 2, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 3]
 [1 5 8]
 [7 2 None]]






next state to be passed:
 [6, 3, None, 1, 4, 5, 7, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 3 None]
 [1 4 5]
 [7 2 8]]






next state to be passed:
 [6, 4, 3, 1, 2, 5, None, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 3]
 [1 2 5]
 [None 7 8]]






next state to be passed:
 [6, 4, 3, 1, 2, 5, 7, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 3]
 [1 2 5]
 [7 8 None]]






next state to be passed:
 [6, 4, 3, 7, 1, 5, 2, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[None 4 5]
 [6 1 2]
 [7 3 8]]






next state to be passed:
 [4, 5, None, 6, 1, 2, 7, 3, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 5 None]
 [6 1 2]
 [7 3 8]]






next state to be passed:
 [7, 1, 5, 3, None, 2, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 1 5]
 [3 None 2]
 [4 6 8]]






next state to be passed:
 [7, 1, 5, 4, 3, 2, None, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 1 5]
 [4 3 2]
 [None 6 8]]






next state to be passed:
 [1, 3, 5, 7, None, 6, 4, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 5]
 [7 None 6]
 [4 8 2]]






next state to be passed:
 [1, 3, None, 7, 6, 5, 4, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 None]
 [7 6 5]
 [4 8 2]]






next state to be passed:
 [3, 5, 2, 1, None, 7, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 5 2]
 [1 None 7]
 [4 6 8]]






next state to be passed:
 [3, 5, 2, 1, 7, 8, 4, 6, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[None 4 5]
 [3 1 8]
 [6 2 7]]






next state to be passed:
 [3, 4, 5, 6, 1, 8, None, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [6 1 8]
 [None 2 7]]






next state to be passed:
 [3, 4, None, 1, 8, 5, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 None]
 [1 8 5]
 [6 2 7]]






next state to be passed:
 [3, 4, 5, 1, 8, 7, 6, 2, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [1 8 7]
 [6 2 None]]






next state to be passed:
 [1, 3, 5, 6, None, 4, 2, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 5]
 [6 None 4]
 [2 7 8]]






next state to be passed:
 [1, 3, None, 6, 4, 5, 2, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 None]
 [6 4 5]
 [2 7 8]]






next state to be passed:
 [1, 3, None, 6, 8, 5, 2, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 None]
 [6 8 5]
 [2 4 7]]






next state to be passed:
 [1, 3, 5, 6, 8, 7, 2, 4, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 3 8]
 [7 2 6]
 [4 5 None]]






next state to be passed:
 [None, 7, 1, 2, 5, 3, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 7 1]
 [2 5 3]
 [4 6 8]]






next state to be passed:
 [7, 5, 1, 2, None, 3, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 5 1]
 [2 None 3]
 [4 6 8]]






next state to be passed:
 [7, 1, 3, 2, 5, 8, None, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 1 3]
 [2 5 8]
 [None 4 6]]






next state to be passed:
 [7, 3, 5, 2, None, 1, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 3 5]
 [2 None 1]
 [4 6 8]]






next state to be passed:
 [7, 3, 5, 2, 1, 8, 4, 6, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 3 5]
 [2 1 8]
 [4 6 None]]






next state to be passed:
 [7, 1, 3, 6, None, 5, 2, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 1 3]
 [6 None 5]
 [2 4 8]]






next state to be passed:
 [None, 1, 3, 7, 6, 5, 2, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 3 5]
 [7 None 8]
 [1 4 6]]






next state to be passed:
 [None, 3, 5, 2, 7, 8, 1, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 3 5]
 [2 7 8]
 [1 4 6]]






next state to be passed:
 [None, 3, 5, 2, 1, 8, 4, 7, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 3 5]
 [2 1 8]
 [4 7 6]]






next state to be passed:
 [2, 3, 5, 4, 1, 8, None, 7, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [4 1 8]
 [None 7 6]]






next state to be passed:
 [2, 3, None, 1, 8, 5, 4, 7, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 None]
 [1 8 5]
 [4 7 6]]






next state to be passed:
 [2, 3, 5, 1, 8, 6, 4, 7, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 5]
 [1 8 6]
 [4 7 None]]






next state to be passed:
 [None, 2, 5, 1, 3, 8, 4, 7, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 2 5]
 [1 3 8]
 [4 7 6]]






next state to be passed:
 [2, 5, None, 1, 3, 8, 4, 7, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 4 2]
 [6 None 3]
 [8 5 7]]






next state to be passed:
 [2, 3, None, 1, 6, 7, 8, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 3 None]
 [1 6 7]
 [8 4 5]]






next state to be passed:
 [2, 6, 3, 1, None, 7, 8, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 6 3]
 [1 None 7]
 [8 4 5]]






next state to be passed:
 [None, 1, 2, 6, 7, 3, 8, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[None 1 2]
 [6 7 3]
 [8 4 5]]






next state to be passed:
 [1, 2, 3, 6, 7, 5, None, 8, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 7 5]
 [None 8 4]]






next state to be passed:
 [1, 2, 3, 6, None, 5, 8, 7, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [6 None 5]
 [8 7 4]]






next state to be passed:
 [6, 1, 3, 2, None, 7, 8, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [2 None 7]
 [8 4 5]]






next state to be passed:
 [6, 1, 3, 8, 2, 7, None, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 3 1]
 [7 None 2]
 [6 8 5]]






next state to be passed:
 [4, 1, 2, 7, 3, 5, None, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 2]
 [7 3 5]
 [None 6 8]]






next state to be passed:
 [4, 1, 2, 7, None, 5, 6, 3, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 2]
 [7 None 5]
 [6 3 8]]






next state to be passed:
 [7, 4, 2, 6, 1, 3, None, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 4 2]
 [6 1 3]
 [None 8 5]]






next state to be passed:
 [4, 2, 3, 7, None, 1, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 2 3]
 [7 None 1]
 [6 8 5]]






next state to be passed:
 [4, 2, 3, 7, 1, 5, 6, 8, None] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 2 3]
 [7 1 5]
 [6 8 None]]






next state to be passed:
 [4, 1, 2, 8, None, 3, 7, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 2]
 [8 None 3]
 [7 6 5]]






next state to be passed:
 [None, 1, 2, 4, 8, 3, 7, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[3 5 4]
 [2 7 1]
 [6 None 8]]






next state to be passed:
 [3, 5, 4, 2, 1, 8, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 5 4]
 [2 1 8]
 [6 None 7]]






next state to be passed:
 [3, 1, 5, 6, 2, 4, 7, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 1 5]
 [6 2 4]
 [7 None 8]]






next state to be passed:
 [3, None, 1, 2, 4, 5, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 None 1]
 [2 4 5]
 [6 7 8]]






next state to be passed:
 [3, 1, 5, 2, 4, 8, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 1 5]
 [2 4 8]
 [6 None 7]]






next state to be passed:
 [3, 1, 5, None, 7, 4, 2, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 1 5]
 [None 7 4]
 [2 6 8]]






next state to be passed:
 [3, 1, 5, 2, 7, None, 6, 8, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 1 5]
 [2 7 None]
 [6 8 4]]






next state to be passed:
 [2, 3, 5, None, 6, 1, 7, 8, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 3 5]
 [4 6 None]
 [1 7 8]]






next state to be passed:
 [3, 5, 8, 2, 4, None, 1, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 5 8]
 [2 4 None]
 [1 6 7]]






next state to be passed:
 [3, 4, 5, None, 2, 8, 1, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [None 2 8]
 [1 6 7]]






next state to be passed:
 [3, 4, 5, 2, 8, None, 1, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [2 8 None]
 [1 6 7]]






next state to be passed:
 [3, 4, 5, 2, 6, 8, 1, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 4 5]
 [2 6 8]
 [1 None 7]]






next state to be passed:
 [3, 5, 8, 2, 1, None, 6, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 5 8]
 [2 1 None]
 [6 4 7]]






next state to be passed:
 [3, 1, 5, None, 2, 8, 6, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 1 5]
 [None 2 8]
 [6 4 7]]






next state to be passed:
 [3, 1, 5, 2, 8, None, 6, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 2 4]
 [None 6 3]
 [7 5 8]]






next state to be passed:
 [1, 2, 4, 6, 3, None, 7, 5, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 4]
 [6 3 None]
 [7 5 8]]






next state to be passed:
 [1, None, 4, 6, 2, 3, 7, 5, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 4]
 [6 2 3]
 [7 5 8]]






next state to be passed:
 [5, 4, 3, 2, 1, None, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 4 3]
 [2 1 None]
 [6 7 8]]






next state to be passed:
 [5, 1, 4, 2, 3, None, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 1 4]
 [2 3 None]
 [6 7 8]]






next state to be passed:
 [5, 1, 4, 2, 7, 3, 6, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 1 4]
 [2 7 3]
 [6 None 8]]






next state to be passed:
 [2, 5, 4, 6, 1, None, 7, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 4]
 [6 1 None]
 [7 8 3]]






next state to be passed:
 [2, 5, 4, 7, 6, 3, 1, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 7 3]
 [None 6 5]
 [2 1 8]]






next state to be passed:
 [4, 7, 3, 2, 6, None, 1, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 7 3]
 [2 6 None]
 [1 8 5]]






next state to be passed:
 [2, 4, 3, 6, 1, None, 8, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 3]
 [6 1 None]
 [8 5 7]]






next state to be passed:
 [2, 4, 3, None, 6, 7, 8, 1, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 3]
 [None 6 7]
 [8 1 5]]






next state to be passed:
 [2, 4, 3, 6, 7, None, 8, 1, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 3]
 [6 7 None]
 [8 1 5]]






next state to be passed:
 [2, None, 3, 6, 4, 7, 8, 1, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 3]
 [6 4 7]
 [8 1 5]]






next state to be passed:
 [2, 4, 3, 8, 7, None, 1, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 3]
 [8 7 None]
 [1 6 5]]






next state to be passed:
 [2, None, 3, 8, 4, 7, 1, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 3 4]
 [6 5 None]
 [7 2 8]]






next state to be passed:
 [1, None, 4, 6, 3, 5, 7, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 4]
 [6 3 5]
 [7 2 8]]






next state to be passed:
 [1, None, 2, 8, 4, 3, 6, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 2]
 [8 4 3]
 [6 7 5]]






next state to be passed:
 [1, 2, 3, 8, 4, 5, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [8 4 5]
 [6 None 7]]






next state to be passed:
 [8, 1, 3, None, 2, 4, 6, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[8 1 3]
 [None 2 4]
 [6 7 5]]






next state to be passed:
 [1, 3, 4, 8, 2, None, 6, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 3 4]
 [8 2 None]
 [6 7 5]]






next state to be passed:
 [1, 2, 3, 8, 7, None, 6, 5, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [8 7 None]
 [6 5 4]]






next state to be passed:
 [2, 3, 4, 1, 8, None, 6, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 6 3]
 [7 1 None]
 [4 8 5]]






next state to be passed:
 [2, 6, 3, None, 7, 5, 4, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 6 3]
 [None 7 5]
 [4 1 8]]






next state to be passed:
 [2, 6, 3, 7, 5, None, 4, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 6 3]
 [7 5 None]
 [4 1 8]]






next state to be passed:
 [2, None, 3, 7, 6, 5, 4, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 3]
 [7 6 5]
 [4 1 8]]






next state to be passed:
 [1, 2, 6, None, 5, 3, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 6]
 [None 5 3]
 [7 4 8]]






next state to be passed:
 [2, 5, 6, None, 1, 3, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 6]
 [None 1 3]
 [7 4 8]]






next state to be passed:
 [2, 5, 6, 1, 4, 3, 7, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 6]
 [1 4 3]
 [7 None 8]]






next state to be passed:
 [2, 6, 3, None, 5, 8, 1, 7, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 6 1]
 [None 5 3]
 [7 4 8]]






next state to be passed:
 [6, 5, 1, None, 2, 3, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 5 1]
 [None 2 3]
 [7 4 8]]






next state to be passed:
 [6, 5, 1, 2, 3, None, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 5 1]
 [2 3 None]
 [7 4 8]]






next state to be passed:
 [6, 5, 1, 2, 4, 3, 7, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 5 1]
 [2 4 3]
 [7 None 8]]






next state to be passed:
 [6, 1, 3, None, 5, 8, 2, 7, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 1 3]
 [None 5 8]
 [2 7 4]]






next state to be passed:
 [6, 3, 5, None, 2, 1, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 3 5]
 [None 2 1]
 [7 4 8]]






next state to be passed:
 [6, None, 5, 2, 3, 1, 7, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 None 5]
 [2 3 1]
 [7 4 8]]






next state to be passed:
 [6, 3, 5, 2, 4, 1, 7, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 None 2]
 [4 3 8]
 [5 6 7]]






next state to be passed:
 [4, 1, 2, 6, 5, 8, 3, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 2]
 [6 5 8]
 [3 None 7]]






next state to be passed:
 [4, None, 1, 5, 8, 2, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 1]
 [5 8 2]
 [6 3 7]]






next state to be passed:
 [5, 4, 2, None, 1, 8, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 4 2]
 [None 1 8]
 [6 3 7]]






next state to be passed:
 [4, 2, 8, 5, 1, None, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 2 8]
 [5 1 None]
 [6 3 7]]






next state to be passed:
 [5, 4, 2, 6, 1, None, 7, 8, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 4 2]
 [6 1 None]
 [7 8 3]]






next state to be passed:
 [5, 4, 2, None, 6, 3, 7, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 4 2]
 [None 6 3]
 [7 1 8]]






next state to be passed:
 [5, 4, 2, 6, 3, None, 7, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 1 2]
 [None 6 8]
 [7 3 5]]






next state to be passed:
 [4, None, 2, 6, 1, 8, 7, 3, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 2]
 [6 1 8]
 [7 3 5]]






next state to be passed:
 [6, 4, 2, 1, 3, None, 7, 5, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 2]
 [1 3 None]
 [7 5 8]]






next state to be passed:
 [6, None, 2, 1, 4, 3, 7, 5, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 None 2]
 [1 4 3]
 [7 5 8]]






next state to be passed:
 [6, 4, 2, 1, 5, 3, 7, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 2]
 [1 5 3]
 [7 None 8]]






next state to be passed:
 [6, 4, 2, 7, 1, 3, 5, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 2]
 [7 1 3]
 [5 None 8]]






next state to be passed:
 [4, 2, 3, None, 6, 1, 7, 5, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 2 3]
 [None 6 1]
 [7 5 8]]






next state to be passed:
 [4, None, 3, 6, 2, 1, 7, 5, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 8 5]
 [None 4 2]
 [6 3 7]]






next state to be passed:
 [1, 8, 5, 4, 2, None, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 5]
 [4 2 None]
 [6 3 7]]






next state to be passed:
 [1, 8, 5, 4, 3, 2, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 5]
 [4 3 2]
 [6 None 7]]






next state to be passed:
 [1, 2, 8, None, 4, 5, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 8]
 [None 4 5]
 [6 3 7]]






next state to be passed:
 [1, None, 8, 4, 2, 5, 6, 3, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 8]
 [4 2 5]
 [6 3 7]]






next state to be passed:
 [1, 2, 8, 4, 3, 5, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 8]
 [4 3 5]
 [6 None 7]]






next state to be passed:
 [1, 2, 8, 4, 5, 7, 6, None, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 8]
 [4 5 7]
 [6 None 3]]






next state to be passed:
 [1, 5, 2, None, 3, 8, 7, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[8 None 2]
 [1 5 3]
 [4 6 7]]






next state to be passed:
 [1, 8, 2, 5, 3, 7, 4, None, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 2]
 [5 3 7]
 [4 None 6]]






next state to be passed:
 [1, 8, 2, None, 6, 3, 5, 4, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 2]
 [None 6 3]
 [5 4 7]]






next state to be passed:
 [1, 8, 2, 5, 6, None, 4, 7, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 2]
 [5 6 None]
 [4 7 3]]






next state to be passed:
 [1, 2, 3, 8, 7, None, 5, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [8 7 None]
 [5 4 6]]






next state to be passed:
 [1, None, 3, 8, 2, 7, 5, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 3]
 [8 2 7]
 [5 4 6]]






next state to be passed:
 [1, 2, 3, 8, 4, 7, 5, None, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 3]
 [8 4 7]
 [5 None 6]]






next state to be passed:
 [2, None, 3, 1, 8, 7, 5, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 None 8]
 [1 3 7]
 [4 5 6]]






next state to be passed:
 [2, 5, 3, 4, 1, None, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 3]
 [4 1 None]
 [6 7 8]]






next state to be passed:
 [2, 5, 3, None, 4, 8, 6, 1, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 3]
 [None 4 8]
 [6 1 7]]






next state to be passed:
 [2, 5, 3, 4, 8, None, 6, 1, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 5 3]
 [4 8 None]
 [6 1 7]]






next state to be passed:
 [2, None, 3, 4, 5, 8, 6, 1, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 3]
 [4 5 8]
 [6 1 7]]






next state to be passed:
 [1, 2, 5, None, 8, 3, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 5]
 [None 8 3]
 [4 6 7]]






next state to be passed:
 [2, 8, 5, None, 1, 3, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 8 5]
 [None 1 3]
 [4 6 7]]






next state to be passed:
 [2, 8, 5, 1, 6, 3, 4, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 1 2]
 [None 6 3]
 [5 8 7]]






next state to be passed:
 [4, 1, 2, 6, 3, None, 5, 8, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 2]
 [6 3 None]
 [5 8 7]]






next state to be passed:
 [4, None, 2, 6, 1, 3, 5, 8, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 2]
 [6 1 3]
 [5 8 7]]






next state to be passed:
 [8, 2, 3, 1, 4, None, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[8 2 3]
 [1 4 None]
 [6 5 7]]






next state to be passed:
 [8, 4, 2, 1, 3, None, 6, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[8 4 2]
 [1 3 None]
 [6 5 7]]






next state to be passed:
 [8, 4, 2, 1, 5, 3, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[8 4 2]
 [1 5 3]
 [6 None 7]]






next state to be passed:
 [1, 8, 2, 6, 4, None, 5, 7, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 2]
 [6 4 None]
 [5 7 3]]






next state to be passed:
 [1, 8, 2, None, 3, 7, 4, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 3 8]
 [6 4 7]
 [2 None 5]]






next state to be passed:
 [1, None, 3, 4, 7, 8, 6, 2, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 3]
 [4 7 8]
 [6 2 5]]






next state to be passed:
 [4, 1, 8, None, 3, 7, 6, 2, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 8]
 [None 3 7]
 [6 2 5]]






next state to be passed:
 [1, 8, 7, 4, 3, None, 6, 2, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 7]
 [4 3 None]
 [6 2 5]]






next state to be passed:
 [2, None, 4, 5, 3, 1, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 4]
 [5 3 1]
 [6 7 8]]






next state to be passed:
 [2, 4, 1, 5, 3, 8, 6, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 4 1]
 [5 3 8]
 [6 None 7]]






next state to be passed:
 [5, 2, 1, None, 4, 3, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[5 2 1]
 [None 4 3]
 [6 7 8]]






next state to be passed:
 [2, 1, 3, 5, 4, None, 6, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 None 3]
 [2 7 5]
 [6 8 1]]






next state to be passed:
 [4, 3, 5, 1, 8, None, 2, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [1 8 None]
 [2 6 7]]






next state to be passed:
 [4, None, 5, 1, 3, 8, 2, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 5]
 [1 3 8]
 [2 6 7]]






next state to be passed:
 [4, 3, 5, 1, 6, 8, 2, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [1 6 8]
 [2 None 7]]






next state to be passed:
 [3, None, 5, 4, 1, 8, 2, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 None 5]
 [4 1 8]
 [2 6 7]]






next state to be passed:
 [3, None, 5, 4, 2, 8, 6, 1, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 None 5]
 [4 2 8]
 [6 1 7]]






next state to be passed:
 [4, 3, 5, 6, 2, 8, 1, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 5]
 [6 2 8]
 [1 None 7]]






next state to be passed:
 [4, None, 3, 2, 8, 5, 6, 1, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 6 3]
 [None 4 2]
 [7 8 5]]






next state to be passed:
 [1, 6, 3, 4, 2, None, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 6 3]
 [4 2 None]
 [7 8 5]]






next state to be passed:
 [1, 6, 3, 4, 8, 2, 7, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 6 3]
 [4 8 2]
 [7 None 5]]






next state to be passed:
 [4, 1, 3, 7, 6, None, 8, 5, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [7 6 None]
 [8 5 2]]






next state to be passed:
 [4, 1, 3, None, 7, 2, 8, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [None 7 2]
 [8 6 5]]






next state to be passed:
 [4, 1, 3, 7, 2, None, 8, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [7 2 None]
 [8 6 5]]






next state to be passed:
 [4, None, 3, 7, 1, 2, 8, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 3]
 [7 1 2]
 [8 6 5]]






next state to be passed:
 [6, 4, 3, 1, 2, None, 7, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[6 3 5]
 [1 4 None]
 [7 2 8]]






next state to be passed:
 [6, 4, 3, None, 2, 5, 1, 7, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 3]
 [None 2 5]
 [1 7 8]]






next state to be passed:
 [6, 4, 3, 7, 1, None, 2, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 3]
 [7 1 None]
 [2 8 5]]






next state to be passed:
 [6, 4, 3, None, 7, 5, 2, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 3]
 [None 7 5]
 [2 1 8]]






next state to be passed:
 [6, 4, 3, 7, 5, None, 2, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 3]
 [7 5 None]
 [2 1 8]]






next state to be passed:
 [6, None, 3, 7, 4, 5, 2, 1, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 None 3]
 [7 4 5]
 [2 1 8]]






next state to be passed:
 [3, None, 5, 4, 6, 1, 7, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 None 5]
 [4 6 1]
 [7 2 8]]






next state to be passed:
 [6, 4, 5, None, 3, 1, 7, 2, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 1 5]
 [7 2 None]
 [3 6 8]]






next state to be passed:
 [4, None, 5, 7, 1, 2, 3, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 5]
 [7 1 2]
 [3 6 8]]






next state to be passed:
 [4, 1, 5, 7, 6, 2, 3, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 5]
 [7 6 2]
 [3 None 8]]






next state to be passed:
 [1, None, 5, 4, 7, 2, 3, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 5]
 [4 7 2]
 [3 6 8]]






next state to be passed:
 [4, None, 5, 3, 1, 7, 6, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 5]
 [3 1 7]
 [6 8 2]]






next state to be passed:
 [4, 1, 5, 3, 8, 7, 6, None, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 5]
 [3 8 7]
 [6 None 2]]






next state to be passed:
 [4, None, 1, 3, 7, 5, 6, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 1]
 [3 7 5]
 [6 8 2]]






next state to be passed:
 [4, 1, 5, None, 6, 3, 7, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 1 3]
 [6 7 5]
 [8 None 2]]






next state to be passed:
 [7, None, 3, 1, 4, 5, 6, 8, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 None 3]
 [1 4 5]
 [6 8 2]]






next state to be passed:
 [1, 7, 3, 6, 4, 5, 8, None, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 3]
 [6 4 5]
 [8 None 2]]






next state to be passed:
 [1, 7, 3, 4, 5, 2, 6, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 3]
 [4 5 2]
 [6 None 8]]






next state to be passed:
 [1, 7, 3, None, 8, 5, 4, 6, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 3]
 [None 8 5]
 [4 6 2]]






next state to be passed:
 [1, 7, 3, 4, 8, None, 6, 2, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 3]
 [4 8 None]
 [6 2 5]]






next state to be passed:
 [2, 1, 3, None, 8, 5, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 1 3]
 [None 8 5]
 [4 6 7]]






next state to be passed:
 [1, 8, 3, None, 2, 5, 4, 6, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 1 3]
 [8 2 5]
 [6 None 7]]






next state to be passed:
 [4, 1, 3, 6, 8, 5, 2, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [6 8 5]
 [2 None 7]]






next state to be passed:
 [8, None, 3, 1, 4, 5, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[8 None 3]
 [1 4 5]
 [6 2 7]]






next state to be passed:
 [1, 8, 3, 6, 4, 5, 2, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 3]
 [6 4 5]
 [2 None 7]]






next state to be passed:
 [1, 8, 3, 4, 5, 7, 6, None, 2] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 3]
 [4 5 7]
 [6 None 2]]






next state to be passed:
 [1, 8, 3, 4, 2, None, 6, 7, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 8 3]
 [4 2 None]
 [6 7 5]]






next state to be passed:
 [4, None, 1, 3, 8, 5, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 1]
 [3 8 5]
 [6 2 7]]






next state to be passed:
 [4, 5, 8, 3, 1, None, 6, 2, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[1 3 8]
 [7 2 6]
 [4 None 5]]






next state to be passed:
 [2, 7, 1, None, 5, 3, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 1]
 [None 5 3]
 [4 6 8]]






next state to be passed:
 [7, 5, 1, None, 2, 3, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 5 1]
 [None 2 3]
 [4 6 8]]






next state to be passed:
 [7, 5, 1, 2, 3, None, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 5 1]
 [2 3 None]
 [4 6 8]]






next state to be passed:
 [7, 5, 1, 2, 6, 3, 4, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 5 1]
 [2 6 3]
 [4 None 8]]






next state to be passed:
 [7, 1, 3, None, 5, 8, 2, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 1 3]
 [None 5 8]
 [2 4 6]]






next state to be passed:
 [7, 3, 5, None, 2, 1, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 3 5]
 [None 2 1]
 [4 6 8]]






next state to be passed:
 [7, None, 5, 2, 3, 1, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[7 1 2]
 [4 6 3]
 [8 None 5]]






next state to be passed:
 [6, None, 2, 1, 7, 3, 4, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 None 2]
 [1 7 3]
 [4 8 5]]






next state to be passed:
 [1, 6, 2, 4, 7, 3, 8, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 6 2]
 [4 7 3]
 [8 None 5]]






next state to be passed:
 [1, 6, 2, 7, 3, 5, 4, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 6 2]
 [7 3 5]
 [4 None 8]]






next state to be passed:
 [1, 6, 2, None, 8, 3, 7, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 6 2]
 [None 8 3]
 [7 4 5]]






next state to be passed:
 [1, 6, 2, 7, 8, None, 4, 5, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 6 2]
 [7 8 None]
 [4 5 3]]






next state to be passed:
 [3, 5, 7, 2, 1, None, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[3 5 7]
 [2 1 None]
 [4 6 8]]






next state to be passed:
 [3, 1, 5, None, 2, 7, 4, 6, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 None 3]
 [5 7 8]
 [1 4 6]]






next state to be passed:
 [2, 7, 3, 5, 4, 8, 1, None, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 3]
 [5 4 8]
 [1 None 6]]






next state to be passed:
 [7, None, 3, 2, 5, 8, 1, 4, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 None 3]
 [2 5 8]
 [1 4 6]]






next state to be passed:
 [2, 7, 3, 4, 1, 8, 5, None, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 3]
 [4 1 8]
 [5 None 6]]






next state to be passed:
 [2, None, 7, 1, 8, 3, 4, 5, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 7]
 [1 8 3]
 [4 5 6]]






next state to be passed:
 [2, None, 7, 6, 5, 3, 1, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 None 7]
 [6 5 3]
 [1 4 8]]






next state to be passed:
 [2, 7, 3, 6, 5, 8, 1, None, 4] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 7 3]
 [6 5 8]
 [1 None 4]]






next state to be passed:
 [6, 2, 3, None, 7, 5, 1, 4, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[4 None 3]
 [6 1 2]
 [8 5 7]]






next state to be passed:
 [4, 1, 3, 6, 5, 2, 8, None, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 1 3]
 [6 5 2]
 [8 None 7]]






next state to be passed:
 [4, None, 1, 6, 2, 3, 8, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 1]
 [6 2 3]
 [8 5 7]]






next state to be passed:
 [1, None, 3, 4, 6, 7, 8, 2, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 3]
 [4 6 7]
 [8 2 5]]






next state to be passed:
 [4, None, 1, 6, 7, 3, 8, 2, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 None 1]
 [6 7 3]
 [8 2 5]]






next state to be passed:
 [6, 4, 3, None, 1, 7, 8, 2, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[6 4 3]
 [None 1 7]
 [8 2 5]]






next state to be passed:
 [4, 3, 7, 6, 1, None, 8, 2, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 7]
 [6 1 None]
 [8 2 5]]






next state to be passed:
 [3, 7, 2, 1, 4, None, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[2 None 8]
 [1 7 3]
 [4 6 5]]






next state to be passed:
 [2, 8, 3, 1, 7, 5, 4, None, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 8 3]
 [1 7 5]
 [4 None 6]]






next state to be passed:
 [2, 8, 3, None, 6, 7, 1, 4, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 8 3]
 [None 6 7]
 [1 4 5]]






next state to be passed:
 [2, 8, 3, 1, 6, None, 4, 5, 7] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[2 8 3]
 [1 6 None]
 [4 5 7]]






next state to be passed:
 [7, 4, 1, None, 3, 2, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 4 1]
 [None 3 2]
 [6 8 5]]






next state to be passed:
 [4, 3, 1, None, 7, 2, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 1]
 [None 7 2]
 [6 8 5]]






next state to be passed:
 [4, 3, 1, 7, 2, None, 6, 8, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[4 3 1]
 [7 2 None]
 [6 8 5]]






next state to be passed:
 [4, 3, 1, 7, 8, 2, 6, None, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]


current state :
 [[7 None 2]
 [1 3 5]
 [4 6 8]]






next state to be passed:
 [7, None, 2, 1, 4, 5, 6, 3, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[7 None 2]
 [1 4 5]
 [6 3 8]]






next state to be passed:
 [1, 7, 2, 6, 4, 5, 3, None, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 2]
 [6 4 5]
 [3 None 8]]






next state to be passed:
 [1, None, 7, 4, 5, 2, 6, 3, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 None 7]
 [4 5 2]
 [6 3 8]]






next state to be passed:
 [1, 2, 5, 4, 7, None, 6, 3, 8] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 2 5]
 [4 7 None]
 [6 3 8]]






next state to be passed:
 [1, 7, 2, 8, 3, 5, 4, None, 6] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 2]
 [8 3 5]
 [4 None 6]]






next state to be passed:
 [1, 7, 2, 8, 6, None, 4, 5, 3] [None, 1, 2, 3, 4, 5, 6, 7, 8]

current state :
 [[1 7 2]
 [8 6 None]
 [4 5 3]]






next state to be passed:
 [7, 2, 3, 1, 8, None, 4, 6, 5] [None, 1, 2, 3, 4, 5, 6, 7, 8]

SystemExit: 